dir: "{{.InterfaceDir}}/../mocks"
pkgname: "mocks"
template: testify

packages:
  github.com/you-humble/rocket-maintenance/order/internal/service/order:
    config:
      all: true
      filename: "mock_{{ snakecase .InterfaceName }}.go"

  github.com/you-humble/rocket-maintenance/inventory/internal/service/part:
    config:
      all: true
      filename: "mock_{{ snakecase .InterfaceName }}.go"

  github.com/you-humble/rocket-maintenance/payment/internal/service/payment:
    config:
      all: true
      filename: "mock_{{ snakecase .InterfaceName }}.go"
