// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: assembly/v1/assembly.proto

package assemblypbv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaidOrderRecord represents the incoming Kafka event "OrderPaid".
//
// Fields:
// - event_uuid: Unique event identifier for idempotency.
// - order_uuid: Identifier of the paid order.
// - user_uuid: Identifier of the user who paid for the order.
// - payment_method: Payment method as a string (value from PaymentMethod).
// - transaction_uuid: Identifier of the payment transaction produced by the payment step.
type PaidOrderRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventUuid       string                 `protobuf:"bytes,1,opt,name=event_uuid,json=eventUuid,proto3" json:"event_uuid,omitempty"`
	OrderUuid       string                 `protobuf:"bytes,2,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	UserUuid        string                 `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TransactionUuid string                 `protobuf:"bytes,5,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaidOrderRecord) Reset() {
	*x = PaidOrderRecord{}
	mi := &file_assembly_v1_assembly_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaidOrderRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaidOrderRecord) ProtoMessage() {}

func (x *PaidOrderRecord) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_assembly_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaidOrderRecord.ProtoReflect.Descriptor instead.
func (*PaidOrderRecord) Descriptor() ([]byte, []int) {
	return file_assembly_v1_assembly_proto_rawDescGZIP(), []int{0}
}

func (x *PaidOrderRecord) GetEventUuid() string {
	if x != nil {
		return x.EventUuid
	}
	return ""
}

func (x *PaidOrderRecord) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *PaidOrderRecord) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *PaidOrderRecord) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *PaidOrderRecord) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

// AssembledShipRecord represents the outgoing Kafka event "ShipAssembled".
//
// Fields:
// - event_uuid: Unique event identifier for idempotency.
// - order_uuid: Identifier of the assembled order.
// - user_uuid: Identifier of the user who owns the order.
// - build_time_sec: Time spent assembling the ship, in seconds.
type AssembledShipRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventUuid     string                 `protobuf:"bytes,1,opt,name=event_uuid,json=eventUuid,proto3" json:"event_uuid,omitempty"`
	OrderUuid     string                 `protobuf:"bytes,2,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	UserUuid      string                 `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	BuildTimeSec  int64                  `protobuf:"varint,4,opt,name=build_time_sec,json=buildTimeSec,proto3" json:"build_time_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssembledShipRecord) Reset() {
	*x = AssembledShipRecord{}
	mi := &file_assembly_v1_assembly_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssembledShipRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssembledShipRecord) ProtoMessage() {}

func (x *AssembledShipRecord) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_assembly_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssembledShipRecord.ProtoReflect.Descriptor instead.
func (*AssembledShipRecord) Descriptor() ([]byte, []int) {
	return file_assembly_v1_assembly_proto_rawDescGZIP(), []int{1}
}

func (x *AssembledShipRecord) GetEventUuid() string {
	if x != nil {
		return x.EventUuid
	}
	return ""
}

func (x *AssembledShipRecord) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *AssembledShipRecord) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *AssembledShipRecord) GetBuildTimeSec() int64 {
	if x != nil {
		return x.BuildTimeSec
	}
	return 0
}

var File_assembly_v1_assembly_proto protoreflect.FileDescriptor

const file_assembly_v1_assembly_proto_rawDesc = "" +
	"\n" +
	"\x1aassembly/v1/assembly.proto\x12\vassembly.v1\"\xbe\x01\n" +
	"\x0fPaidOrderRecord\x12\x1d\n" +
	"\n" +
	"event_uuid\x18\x01 \x01(\tR\teventUuid\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x02 \x01(\tR\torderUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x03 \x01(\tR\buserUuid\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12)\n" +
	"\x10transaction_uuid\x18\x05 \x01(\tR\x0ftransactionUuid\"\x96\x01\n" +
	"\x13AssembledShipRecord\x12\x1d\n" +
	"\n" +
	"event_uuid\x18\x01 \x01(\tR\teventUuid\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x02 \x01(\tR\torderUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x03 \x01(\tR\buserUuid\x12$\n" +
	"\x0ebuild_time_sec\x18\x04 \x01(\x03R\fbuildTimeSecBTZRgithub.com/you-humble/rocket-maintenance/shared/pkg/proto/assembly/v1;assemblypbv1b\x06proto3"

var (
	file_assembly_v1_assembly_proto_rawDescOnce sync.Once
	file_assembly_v1_assembly_proto_rawDescData []byte
)

func file_assembly_v1_assembly_proto_rawDescGZIP() []byte {
	file_assembly_v1_assembly_proto_rawDescOnce.Do(func() {
		file_assembly_v1_assembly_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assembly_v1_assembly_proto_rawDesc), len(file_assembly_v1_assembly_proto_rawDesc)))
	})
	return file_assembly_v1_assembly_proto_rawDescData
}

var (
	file_assembly_v1_assembly_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
	file_assembly_v1_assembly_proto_goTypes  = []any{
		(*PaidOrderRecord)(nil),     // 0: assembly.v1.PaidOrderRecord
		(*AssembledShipRecord)(nil), // 1: assembly.v1.AssembledShipRecord
	}
)

var file_assembly_v1_assembly_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_assembly_v1_assembly_proto_init() }
func file_assembly_v1_assembly_proto_init() {
	if File_assembly_v1_assembly_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assembly_v1_assembly_proto_rawDesc), len(file_assembly_v1_assembly_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assembly_v1_assembly_proto_goTypes,
		DependencyIndexes: file_assembly_v1_assembly_proto_depIdxs,
		MessageInfos:      file_assembly_v1_assembly_proto_msgTypes,
	}.Build()
	File_assembly_v1_assembly_proto = out.File
	file_assembly_v1_assembly_proto_goTypes = nil
	file_assembly_v1_assembly_proto_depIdxs = nil
}
