// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/you-humble/rocket-maintenance/inventory/internal/model"
)

// NewMockPartRepository creates a new instance of MockPartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPartRepository {
	mock := &MockPartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPartRepository is an autogenerated mock type for the PartRepository type
type MockPartRepository struct {
	mock.Mock
}

type MockPartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPartRepository) EXPECT() *MockPartRepository_Expecter {
	return &MockPartRepository_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockPartRepository
func (_mock *MockPartRepository) List(ctx context.Context) ([]*model.Part, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.Part, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.Part); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPartRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPartRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPartRepository_Expecter) List(ctx interface{}) *MockPartRepository_List_Call {
	return &MockPartRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockPartRepository_List_Call) Run(run func(ctx context.Context)) *MockPartRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPartRepository_List_Call) Return(parts []*model.Part, err error) *MockPartRepository_List_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *MockPartRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]*model.Part, error)) *MockPartRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// PartByID provides a mock function for the type MockPartRepository
func (_mock *MockPartRepository) PartByID(ctx context.Context, id string) (*model.Part, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for PartByID")
	}

	var r0 *model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Part, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Part); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPartRepository_PartByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PartByID'
type MockPartRepository_PartByID_Call struct {
	*mock.Call
}

// PartByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPartRepository_Expecter) PartByID(ctx interface{}, id interface{}) *MockPartRepository_PartByID_Call {
	return &MockPartRepository_PartByID_Call{Call: _e.mock.On("PartByID", ctx, id)}
}

func (_c *MockPartRepository_PartByID_Call) Run(run func(ctx context.Context, id string)) *MockPartRepository_PartByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPartRepository_PartByID_Call) Return(part *model.Part, err error) *MockPartRepository_PartByID_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *MockPartRepository_PartByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Part, error)) *MockPartRepository_PartByID_Call {
	_c.Call.Return(run)
	return _c
}
