FROM golang:1.25.4 AS builder

WORKDIR /src

COPY notification/go.mod notification/go.sum ./notification/
COPY shared/go.mod shared/go.sum ./shared/
COPY platform/go.mod platform/go.sum ./platform/

WORKDIR /src/notification
RUN go mod download

WORKDIR /src
COPY notification ./notification
COPY shared ./shared
COPY platform ./platform

WORKDIR /src/notification
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -trimpath -ldflags="-s -w" \
    -o /bin/notification ./cmd/notification

FROM alpine:3.21.3 AS runtime

WORKDIR /app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder /bin/notification /app/notification

RUN chown -R appuser:appgroup /app

USER appuser

EXPOSE 50051

ENTRYPOINT [ "/app/notification" ]
