// Code generated by ogen, DO NOT EDIT.

package orderv1

import (
	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

// Merged schema.
// Ref: #/components/schemas/bad_gateway_error
type BadGatewayError struct {
	// HTTP-error code.
	Code OptInt32 `json:"code"`
	// Human-readable description of the error.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadGatewayError) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadGatewayError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadGatewayError) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadGatewayError) SetMessage(val OptString) {
	s.Message = val
}

func (*BadGatewayError) createOrderRes() {}
func (*BadGatewayError) payOrderRes()    {}

// Merged schema.
// Ref: #/components/schemas/bad_request_error
type BadRequestError struct {
	// HTTP-error code.
	Code OptInt32 `json:"code"`
	// Human-readable description of the error.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val OptString) {
	s.Message = val
}

func (*BadRequestError) cancelOrderRes()    {}
func (*BadRequestError) createOrderRes()    {}
func (*BadRequestError) getOrderByUUIDRes() {}
func (*BadRequestError) payOrderRes()       {}

// CancelOrderNoContent is response for CancelOrder operation.
type CancelOrderNoContent struct{}

func (*CancelOrderNoContent) cancelOrderRes() {}

// Merged schema.
// Ref: #/components/schemas/conflict_error
type ConflictError struct {
	// HTTP-error code.
	Code OptInt32 `json:"code"`
	// Human-readable description of the error.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *ConflictError) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ConflictError) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val OptString) {
	s.Message = val
}

func (*ConflictError) cancelOrderRes() {}
func (*ConflictError) payOrderRes()    {}

// Request body for creating a new spacecraft build order.
// Ref: #/components/schemas/create_order_request
type CreateOrderRequest struct {
	// UUID of the user placing the spacecraft build order.
	UserUUID uuid.UUID `json:"user_uuid"`
	// List of UUIDs of spacecraft parts included in the order.
	PartUuids []uuid.UUID `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// Response returned after successfully creating a spacecraft build order.
// Ref: #/components/schemas/create_order_response
type CreateOrderResponse struct {
	// UUID of the newly created spacecraft build order.
	UUID uuid.UUID `json:"uuid"`
	// Total price formatted with 2 fraction digits (e.g. "123.45").
	TotalPrice string `json:"total_price"`
}

// GetUUID returns the value of UUID.
func (s *CreateOrderResponse) GetUUID() uuid.UUID {
	return s.UUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() string {
	return s.TotalPrice
}

// SetUUID sets the value of UUID.
func (s *CreateOrderResponse) SetUUID(val uuid.UUID) {
	s.UUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val string) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) createOrderRes() {}

// Merged schema.
// Ref: #/components/schemas/forbidden_error
type ForbiddenError struct {
	// HTTP-error code.
	Code OptInt32 `json:"code"`
	// Human-readable description of the error.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *ForbiddenError) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ForbiddenError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ForbiddenError) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ForbiddenError) SetMessage(val OptString) {
	s.Message = val
}

func (*ForbiddenError) cancelOrderRes()    {}
func (*ForbiddenError) createOrderRes()    {}
func (*ForbiddenError) getOrderByUUIDRes() {}
func (*ForbiddenError) payOrderRes()       {}

// Merged schema.
// Ref: #/components/schemas/internal_server_error
type InternalServerError struct {
	// HTTP-error code.
	Code OptInt32 `json:"code"`
	// Human-readable description of the error.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val OptString) {
	s.Message = val
}

func (*InternalServerError) cancelOrderRes()    {}
func (*InternalServerError) createOrderRes()    {}
func (*InternalServerError) getOrderByUUIDRes() {}
func (*InternalServerError) payOrderRes()       {}

// Merged schema.
// Ref: #/components/schemas/not_found_error
type NotFoundError struct {
	// HTTP-error code.
	Code OptInt32 `json:"code"`
	// Human-readable description of the error.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val OptString) {
	s.Message = val
}

func (*NotFoundError) cancelOrderRes()    {}
func (*NotFoundError) createOrderRes()    {}
func (*NotFoundError) getOrderByUUIDRes() {}
func (*NotFoundError) payOrderRes()       {}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilPaymentMethod returns new OptNilPaymentMethod with value set to v.
func NewOptNilPaymentMethod(v PaymentMethod) OptNilPaymentMethod {
	return OptNilPaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptNilPaymentMethod is optional nullable PaymentMethod.
type OptNilPaymentMethod struct {
	Value PaymentMethod
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilPaymentMethod was set.
func (o OptNilPaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilPaymentMethod) Reset() {
	var v PaymentMethod
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilPaymentMethod) SetTo(v PaymentMethod) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilPaymentMethod) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilPaymentMethod) SetToNull() {
	o.Set = true
	o.Null = true
	var v PaymentMethod
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilPaymentMethod) Get() (v PaymentMethod, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilPaymentMethod) Or(d PaymentMethod) PaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v uuid.UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable uuid.UUID.
type OptNilUUID struct {
	Value uuid.UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Full representation of a spacecraft build order stored in internal storage.
// Ref: #/components/schemas/order
type Order struct {
	// Unique identifier of the order.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// UUID of the user who created the order.
	UserUUID uuid.UUID `json:"user_uuid"`
	// List of UUIDs of spacecraft parts included in the order.
	PartUuids []uuid.UUID `json:"part_uuids"`
	// Total price formatted with 2 fraction digits (e.g. "123.45").
	TotalPrice string `json:"total_price"`
	// UUID of the payment transaction (present if the order is paid).
	TransactionUUID OptNilUUID `json:"transaction_uuid"`
	// Payment method used to pay for the order (present if the order is paid).
	PaymentMethod OptNilPaymentMethod `json:"payment_method"`
	Status        OrderStatus         `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *Order) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *Order) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *Order) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *Order) GetTotalPrice() string {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *Order) GetTransactionUUID() OptNilUUID {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *Order) GetPaymentMethod() OptNilPaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *Order) GetStatus() OrderStatus {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *Order) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *Order) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *Order) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *Order) SetTotalPrice(val string) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *Order) SetTransactionUUID(val OptNilUUID) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *Order) SetPaymentMethod(val OptNilPaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *Order) SetStatus(val OrderStatus) {
	s.Status = val
}

func (*Order) getOrderByUUIDRes() {}

// Status of the spacecraft build order.
// Ref: #/components/schemas/order_status
type OrderStatus string

const (
	OrderStatusPENDINGPAYMENT OrderStatus = "PENDING_PAYMENT"
	OrderStatusPAID           OrderStatus = "PAID"
	OrderStatusCOMPLETED      OrderStatus = "COMPLETED"
	OrderStatusCANCELLED      OrderStatus = "CANCELLED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusPENDINGPAYMENT,
		OrderStatusPAID,
		OrderStatusCOMPLETED,
		OrderStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusPENDINGPAYMENT:
		return []byte(s), nil
	case OrderStatusPAID:
		return []byte(s), nil
	case OrderStatusCOMPLETED:
		return []byte(s), nil
	case OrderStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusPENDINGPAYMENT:
		*s = OrderStatusPENDINGPAYMENT
		return nil
	case OrderStatusPAID:
		*s = OrderStatusPAID
		return nil
	case OrderStatusCOMPLETED:
		*s = OrderStatusCOMPLETED
		return nil
	case OrderStatusCANCELLED:
		*s = OrderStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Request body for paying a spacecraft build order.
// Ref: #/components/schemas/pay_order_request
type PayOrderRequest struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// Response returned after successfully paying a spacecraft build order.
// Ref: #/components/schemas/pay_order_response
type PayOrderResponse struct {
	// UUID of the payment transaction.
	TransactionUUID uuid.UUID `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderResponse) GetTransactionUUID() uuid.UUID {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderResponse) SetTransactionUUID(val uuid.UUID) {
	s.TransactionUUID = val
}

func (*PayOrderResponse) payOrderRes() {}

// Payment method used to pay for the spacecraft build order.
// Ref: #/components/schemas/payment_method
type PaymentMethod string

const (
	PaymentMethodPAYMENTMETHODUNKNOWN       PaymentMethod = "PAYMENT_METHOD_UNKNOWN"
	PaymentMethodPAYMENTMETHODCARD          PaymentMethod = "PAYMENT_METHOD_CARD"
	PaymentMethodPAYMENTMETHODSBP           PaymentMethod = "PAYMENT_METHOD_SBP"
	PaymentMethodPAYMENTMETHODCREDITCARD    PaymentMethod = "PAYMENT_METHOD_CREDIT_CARD"
	PaymentMethodPAYMENTMETHODINVESTORMONEY PaymentMethod = "PAYMENT_METHOD_INVESTOR_MONEY"
)

// AllValues returns all PaymentMethod values.
func (PaymentMethod) AllValues() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodPAYMENTMETHODUNKNOWN,
		PaymentMethodPAYMENTMETHODCARD,
		PaymentMethodPAYMENTMETHODSBP,
		PaymentMethodPAYMENTMETHODCREDITCARD,
		PaymentMethodPAYMENTMETHODINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PaymentMethodPAYMENTMETHODUNKNOWN:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODCARD:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODSBP:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODCREDITCARD:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentMethod) UnmarshalText(data []byte) error {
	switch PaymentMethod(data) {
	case PaymentMethodPAYMENTMETHODUNKNOWN:
		*s = PaymentMethodPAYMENTMETHODUNKNOWN
		return nil
	case PaymentMethodPAYMENTMETHODCARD:
		*s = PaymentMethodPAYMENTMETHODCARD
		return nil
	case PaymentMethodPAYMENTMETHODSBP:
		*s = PaymentMethodPAYMENTMETHODSBP
		return nil
	case PaymentMethodPAYMENTMETHODCREDITCARD:
		*s = PaymentMethodPAYMENTMETHODCREDITCARD
		return nil
	case PaymentMethodPAYMENTMETHODINVESTORMONEY:
		*s = PaymentMethodPAYMENTMETHODINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
// Ref: #/components/schemas/rate_limit_error
type RateLimitError struct {
	// HTTP-error code.
	Code OptInt32 `json:"code"`
	// Human-readable description of the error.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *RateLimitError) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *RateLimitError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *RateLimitError) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *RateLimitError) SetMessage(val OptString) {
	s.Message = val
}

func (*RateLimitError) cancelOrderRes()    {}
func (*RateLimitError) createOrderRes()    {}
func (*RateLimitError) getOrderByUUIDRes() {}
func (*RateLimitError) payOrderRes()       {}

// Merged schema.
// Ref: #/components/schemas/service_unavailable_error
type ServiceUnavailableError struct {
	// HTTP-error code.
	Code OptInt32 `json:"code"`
	// Human-readable description of the error.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *ServiceUnavailableError) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ServiceUnavailableError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ServiceUnavailableError) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ServiceUnavailableError) SetMessage(val OptString) {
	s.Message = val
}

func (*ServiceUnavailableError) createOrderRes() {}
func (*ServiceUnavailableError) payOrderRes()    {}

// Merged schema.
// Ref: #/components/schemas/unauthorized_error
type UnauthorizedError struct {
	// HTTP-error code.
	Code OptInt32 `json:"code"`
	// Human-readable description of the error.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *UnauthorizedError) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *UnauthorizedError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *UnauthorizedError) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *UnauthorizedError) SetMessage(val OptString) {
	s.Message = val
}

func (*UnauthorizedError) cancelOrderRes()    {}
func (*UnauthorizedError) createOrderRes()    {}
func (*UnauthorizedError) getOrderByUUIDRes() {}
func (*UnauthorizedError) payOrderRes()       {}

// Merged schema.
// Ref: #/components/schemas/validation_error
type ValidationError struct {
	// HTTP-error code.
	Code OptInt32 `json:"code"`
	// Human-readable description of the error.
	Message OptString `json:"message"`
	// Detailed validation error descriptions.
	Details []string `json:"details"`
}

// GetCode returns the value of Code.
func (s *ValidationError) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ValidationError) GetMessage() OptString {
	return s.Message
}

// GetDetails returns the value of Details.
func (s *ValidationError) GetDetails() []string {
	return s.Details
}

// SetCode sets the value of Code.
func (s *ValidationError) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ValidationError) SetMessage(val OptString) {
	s.Message = val
}

// SetDetails sets the value of Details.
func (s *ValidationError) SetDetails(val []string) {
	s.Details = val
}

func (*ValidationError) createOrderRes() {}
func (*ValidationError) payOrderRes()    {}
