// Code generated by ogen, DO NOT EDIT.
package orderv1

type CancelOrderRes interface {
	cancelOrderRes()
}

type CreateOrderRes interface {
	createOrderRes()
}

type GetOrderByUUIDRes interface {
	getOrderByUUIDRes()
}

type PayOrderRes interface {
	payOrderRes()
}
