// Code generated by ogen, DO NOT EDIT.

package orderv1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrder implements CancelOrder operation.
	//
	// Cancels an existing order.   If the order is in PENDING_PAYMENT status, it is changed to CANCELLED.
	//    If the order is already PAID, a 409 Conflict error is returned and the order remains unchanged.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (CancelOrderRes, error)
	// CreateOrder implements CreateOrder operation.
	//
	// Creates a new order based on the provided user UUID and list of part UUIDs. The service fetches
	// parts via InventoryService.ListParts, verifies that all parts exist, calculates the total price,
	// generates order_uuid, and saves the order with status PENDING_PAYMENT.
	//
	// POST /api/v1/orders
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (CreateOrderRes, error)
	// GetOrderByUUID implements GetOrderByUUID operation.
	//
	// Returns full information about an order by its UUID.   If the order is found, all fields are
	// returned, including payment information when applicable. If the order does not exist, a 404 error
	// is returned.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrderByUUID(ctx context.Context, params GetOrderByUUIDParams) (GetOrderByUUIDRes, error)
	// PayOrder implements PayOrder operation.
	//
	// Processes payment for a previously created order.   The service looks up the order by order_uuid.
	// If the order exists and is in PENDING_PAYMENT status, it calls PaymentService.PayOrder with
	// user_uuid, order_uuid, and payment_method. After a successful payment, the order status is set to
	// PAID and transaction_uuid and payment_method are stored.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (PayOrderRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
