// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/you-humble/rocket-maintenance/order/internal/model"
)

// NewMockOrderPaidSender creates a new instance of MockOrderPaidSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderPaidSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderPaidSender {
	mock := &MockOrderPaidSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderPaidSender is an autogenerated mock type for the OrderPaidSender type
type MockOrderPaidSender struct {
	mock.Mock
}

type MockOrderPaidSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderPaidSender) EXPECT() *MockOrderPaidSender_Expecter {
	return &MockOrderPaidSender_Expecter{mock: &_m.Mock}
}

// SendOrderPaid provides a mock function for the type MockOrderPaidSender
func (_mock *MockOrderPaidSender) SendOrderPaid(ctx context.Context, event model.PaidOrder) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SendOrderPaid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PaidOrder) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderPaidSender_SendOrderPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOrderPaid'
type MockOrderPaidSender_SendOrderPaid_Call struct {
	*mock.Call
}

// SendOrderPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.PaidOrder
func (_e *MockOrderPaidSender_Expecter) SendOrderPaid(ctx interface{}, event interface{}) *MockOrderPaidSender_SendOrderPaid_Call {
	return &MockOrderPaidSender_SendOrderPaid_Call{Call: _e.mock.On("SendOrderPaid", ctx, event)}
}

func (_c *MockOrderPaidSender_SendOrderPaid_Call) Run(run func(ctx context.Context, event model.PaidOrder)) *MockOrderPaidSender_SendOrderPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.PaidOrder
		if args[1] != nil {
			arg1 = args[1].(model.PaidOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderPaidSender_SendOrderPaid_Call) Return(err error) *MockOrderPaidSender_SendOrderPaid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderPaidSender_SendOrderPaid_Call) RunAndReturn(run func(ctx context.Context, event model.PaidOrder) error) *MockOrderPaidSender_SendOrderPaid_Call {
	_c.Call.Return(run)
	return _c
}
