// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/you-humble/rocket-maintenance/order/internal/model"
)

// NewMockInventoryClient creates a new instance of MockInventoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryClient {
	mock := &MockInventoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryClient is an autogenerated mock type for the InventoryClient type
type MockInventoryClient struct {
	mock.Mock
}

type MockInventoryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryClient) EXPECT() *MockInventoryClient_Expecter {
	return &MockInventoryClient_Expecter{mock: &_m.Mock}
}

// ListParts provides a mock function for the type MockInventoryClient
func (_mock *MockInventoryClient) ListParts(ctx context.Context, filter model.PartsFilter) ([]model.Part, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartsFilter) ([]model.Part, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartsFilter) []model.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.PartsFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInventoryClient_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type MockInventoryClient_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.PartsFilter
func (_e *MockInventoryClient_Expecter) ListParts(ctx interface{}, filter interface{}) *MockInventoryClient_ListParts_Call {
	return &MockInventoryClient_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filter)}
}

func (_c *MockInventoryClient_ListParts_Call) Run(run func(ctx context.Context, filter model.PartsFilter)) *MockInventoryClient_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.PartsFilter
		if args[1] != nil {
			arg1 = args[1].(model.PartsFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryClient_ListParts_Call) Return(parts []model.Part, err error) *MockInventoryClient_ListParts_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *MockInventoryClient_ListParts_Call) RunAndReturn(run func(ctx context.Context, filter model.PartsFilter) ([]model.Part, error)) *MockInventoryClient_ListParts_Call {
	_c.Call.Return(run)
	return _c
}
