// Code generated by ogen, DO NOT EDIT.

package null

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrder implements CancelOrder operation.
	//
	// Отменяет существующий заказ на сборку космического
	// корабля.
	// Ограничения:
	// - заказ должен существовать;
	// - заказ не должен быть уже отменён;
	// - заказ не должен быть уже оплачен (или может
	// требоваться возврат денег — зависит от
	// бизнес‑логики).
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (CancelOrderRes, error)
	// CreateOrder implements CreateOrder operation.
	//
	// Создаёт новый заказ на сборку космического корабля
	// из набора деталей.
	// Валидация:
	// - все указанные детали должны существовать;
	// - количество каждой детали должно быть положительным;
	// - суммарная стоимость вычисляется на стороне сервиса.
	//
	// POST /api/v1/orders
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (CreateOrderRes, error)
	// GetOrder implements GetOrder operation.
	//
	// Возвращает информацию о заказе на сборку
	// космического корабля по его UUID.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrder(ctx context.Context, params GetOrderParams) (GetOrderRes, error)
	// PayOrder implements PayOrder operation.
	//
	// Обрабатывает оплату ранее созданного заказа на
	// сборку космического корабля.
	// Ограничения:
	// - заказ должен существовать;
	// - заказ не должен быть отменён;
	// - заказ не должен быть уже оплачен.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (PayOrderRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
