// Code generated by ogen, DO NOT EDIT.

package null

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOrder implements CancelOrder operation.
//
// Отменяет существующий заказ на сборку космического
// корабля.
// Ограничения:
// - заказ должен существовать;
// - заказ не должен быть уже отменён;
// - заказ не должен быть уже оплачен (или может
// требоваться возврат денег — зависит от
// бизнес‑логики).
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) CancelOrder(ctx context.Context, params CancelOrderParams) (r CancelOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrder implements CreateOrder operation.
//
// Создаёт новый заказ на сборку космического корабля
// из набора деталей.
// Валидация:
// - все указанные детали должны существовать;
// - количество каждой детали должно быть положительным;
// - суммарная стоимость вычисляется на стороне сервиса.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderRequest) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrder implements GetOrder operation.
//
// Возвращает информацию о заказе на сборку
// космического корабля по его UUID.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrder(ctx context.Context, params GetOrderParams) (r GetOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrder implements PayOrder operation.
//
// Обрабатывает оплату ранее созданного заказа на
// сборку космического корабля.
// Ограничения:
// - заказ должен существовать;
// - заказ не должен быть отменён;
// - заказ не должен быть уже оплачен.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (r PayOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
