// Code generated by ogen, DO NOT EDIT.

package null

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Merged schema.
// Ref: #/components/schemas/bad_gateway_error
type BadGatewayError struct {
	// Merged property.
	Code string `json:"code"`
	// Merged property.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadGatewayError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadGatewayError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadGatewayError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadGatewayError) SetMessage(val string) {
	s.Message = val
}

func (*BadGatewayError) cancelOrderRes() {}
func (*BadGatewayError) createOrderRes() {}
func (*BadGatewayError) getOrderRes()    {}
func (*BadGatewayError) payOrderRes()    {}

// Merged schema.
// Ref: #/components/schemas/bad_request_error
type BadRequestError struct {
	// Merged property.
	Code string `json:"code"`
	// Merged property.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val string) {
	s.Message = val
}

func (*BadRequestError) cancelOrderRes() {}
func (*BadRequestError) payOrderRes()    {}

// Response body after a successful cancellation of an order.
// Ref: #/components/schemas/cancel_order_response
type CancelOrderResponse struct {
	Order Order `json:"order"`
}

// GetOrder returns the value of Order.
func (s *CancelOrderResponse) GetOrder() Order {
	return s.Order
}

// SetOrder sets the value of Order.
func (s *CancelOrderResponse) SetOrder(val Order) {
	s.Order = val
}

func (*CancelOrderResponse) cancelOrderRes() {}

// Merged schema.
// Ref: #/components/schemas/conflict_error
type ConflictError struct {
	// Merged property.
	Code string `json:"code"`
	// Merged property.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ConflictError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ConflictError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val string) {
	s.Message = val
}

func (*ConflictError) cancelOrderRes() {}
func (*ConflictError) payOrderRes()    {}

// Item of the order to be created (spacecraft part and its quantity).
// Ref: #/components/schemas/create_order_item
type CreateOrderItem struct {
	// Identifier of the spacecraft part to be included in the order.
	PartID string `json:"part_id"`
	// Quantity of the given part.
	Quantity int32 `json:"quantity"`
}

// GetPartID returns the value of PartID.
func (s *CreateOrderItem) GetPartID() string {
	return s.PartID
}

// GetQuantity returns the value of Quantity.
func (s *CreateOrderItem) GetQuantity() int32 {
	return s.Quantity
}

// SetPartID sets the value of PartID.
func (s *CreateOrderItem) SetPartID(val string) {
	s.PartID = val
}

// SetQuantity sets the value of Quantity.
func (s *CreateOrderItem) SetQuantity(val int32) {
	s.Quantity = val
}

// Request body for creating a new spacecraft build order.
// Ref: #/components/schemas/create_order_request
type CreateOrderRequest struct {
	// List of parts to include in the new order.
	Items []CreateOrderItem `json:"items"`
}

// GetItems returns the value of Items.
func (s *CreateOrderRequest) GetItems() []CreateOrderItem {
	return s.Items
}

// SetItems sets the value of Items.
func (s *CreateOrderRequest) SetItems(val []CreateOrderItem) {
	s.Items = val
}

// Response body for a successfully created order.
// Ref: #/components/schemas/create_order_response
type CreateOrderResponse struct {
	Order Order `json:"order"`
}

// GetOrder returns the value of Order.
func (s *CreateOrderResponse) GetOrder() Order {
	return s.Order
}

// SetOrder sets the value of Order.
func (s *CreateOrderResponse) SetOrder(val Order) {
	s.Order = val
}

func (*CreateOrderResponse) createOrderRes() {}

// Merged schema.
// Ref: #/components/schemas/forbidden_error
type ForbiddenError struct {
	// Merged property.
	Code string `json:"code"`
	// Merged property.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ForbiddenError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ForbiddenError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ForbiddenError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ForbiddenError) SetMessage(val string) {
	s.Message = val
}

func (*ForbiddenError) cancelOrderRes() {}
func (*ForbiddenError) createOrderRes() {}
func (*ForbiddenError) getOrderRes()    {}
func (*ForbiddenError) payOrderRes()    {}

// Generic error response object for the Order Service.
// Ref: #/components/schemas/generic_error
type GenericError struct {
	// Short, machine-readable error code.
	Code string `json:"code"`
	// Human-readable description of the error.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val string) {
	s.Message = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

// Merged schema.
// Ref: #/components/schemas/internal_server_error
type InternalServerError struct {
	// Merged property.
	Code string `json:"code"`
	// Merged property.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerError) cancelOrderRes() {}
func (*InternalServerError) createOrderRes() {}
func (*InternalServerError) getOrderRes()    {}
func (*InternalServerError) payOrderRes()    {}

// Merged schema.
// Ref: #/components/schemas/not_found_error
type NotFoundError struct {
	// Merged property.
	Code string `json:"code"`
	// Merged property.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) cancelOrderRes() {}
func (*NotFoundError) getOrderRes()    {}
func (*NotFoundError) payOrderRes()    {}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v uuid.UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable uuid.UUID.
type OptNilUUID struct {
	Value uuid.UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentMethod returns new OptPaymentMethod with value set to v.
func NewOptPaymentMethod(v PaymentMethod) OptPaymentMethod {
	return OptPaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptPaymentMethod is optional PaymentMethod.
type OptPaymentMethod struct {
	Value PaymentMethod
	Set   bool
}

// IsSet returns true if OptPaymentMethod was set.
func (o OptPaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentMethod) Reset() {
	var v PaymentMethod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentMethod) SetTo(v PaymentMethod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentMethod) Get() (v PaymentMethod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentMethod) Or(d PaymentMethod) PaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Spacecraft build order.
// Ref: #/components/schemas/order
type Order struct {
	// UUID of the order.
	UUID   uuid.UUID   `json:"uuid"`
	Status OrderStatus `json:"status"`
	// List of parts included in the order.
	Items []OrderItem `json:"items"`
	// Total price of the entire order.
	TotalPrice float64 `json:"total_price"`
	// Timestamp when the order was created.
	CreatedAt time.Time `json:"created_at"`
	// Timestamp when the order was last updated.
	UpdatedAt     time.Time        `json:"updated_at"`
	PaymentMethod OptPaymentMethod `json:"payment_method"`
	// Payment transaction UUID (nullable if not paid).
	TransactionUUID OptNilUUID `json:"transaction_uuid"`
}

// GetUUID returns the value of UUID.
func (s *Order) GetUUID() uuid.UUID {
	return s.UUID
}

// GetStatus returns the value of Status.
func (s *Order) GetStatus() OrderStatus {
	return s.Status
}

// GetItems returns the value of Items.
func (s *Order) GetItems() []OrderItem {
	return s.Items
}

// GetTotalPrice returns the value of TotalPrice.
func (s *Order) GetTotalPrice() float64 {
	return s.TotalPrice
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Order) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Order) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *Order) GetPaymentMethod() OptPaymentMethod {
	return s.PaymentMethod
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *Order) GetTransactionUUID() OptNilUUID {
	return s.TransactionUUID
}

// SetUUID sets the value of UUID.
func (s *Order) SetUUID(val uuid.UUID) {
	s.UUID = val
}

// SetStatus sets the value of Status.
func (s *Order) SetStatus(val OrderStatus) {
	s.Status = val
}

// SetItems sets the value of Items.
func (s *Order) SetItems(val []OrderItem) {
	s.Items = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *Order) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Order) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Order) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *Order) SetPaymentMethod(val OptPaymentMethod) {
	s.PaymentMethod = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *Order) SetTransactionUUID(val OptNilUUID) {
	s.TransactionUUID = val
}

func (*Order) getOrderRes() {}

// Single item (spacecraft part) included in the order.
// Ref: #/components/schemas/order_item
type OrderItem struct {
	// Identifier of the spacecraft part.
	PartID string `json:"part_id"`
	// Quantity of the given part in the order.
	Quantity int32 `json:"quantity"`
	// Price per single unit of the part.
	UnitPrice float64 `json:"unit_price"`
	// Total price for this item (quantity * unit_price).
	TotalPrice float64 `json:"total_price"`
}

// GetPartID returns the value of PartID.
func (s *OrderItem) GetPartID() string {
	return s.PartID
}

// GetQuantity returns the value of Quantity.
func (s *OrderItem) GetQuantity() int32 {
	return s.Quantity
}

// GetUnitPrice returns the value of UnitPrice.
func (s *OrderItem) GetUnitPrice() float64 {
	return s.UnitPrice
}

// GetTotalPrice returns the value of TotalPrice.
func (s *OrderItem) GetTotalPrice() float64 {
	return s.TotalPrice
}

// SetPartID sets the value of PartID.
func (s *OrderItem) SetPartID(val string) {
	s.PartID = val
}

// SetQuantity sets the value of Quantity.
func (s *OrderItem) SetQuantity(val int32) {
	s.Quantity = val
}

// SetUnitPrice sets the value of UnitPrice.
func (s *OrderItem) SetUnitPrice(val float64) {
	s.UnitPrice = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *OrderItem) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

// Status of the spacecraft build order.
// Ref: #/components/schemas/order_status
type OrderStatus string

const (
	OrderStatusCREATED   OrderStatus = "CREATED"
	OrderStatusPAID      OrderStatus = "PAID"
	OrderStatusCANCELLED OrderStatus = "CANCELLED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusCREATED,
		OrderStatusPAID,
		OrderStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusCREATED:
		return []byte(s), nil
	case OrderStatusPAID:
		return []byte(s), nil
	case OrderStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusCREATED:
		*s = OrderStatusCREATED
		return nil
	case OrderStatusPAID:
		*s = OrderStatusPAID
		return nil
	case OrderStatusCANCELLED:
		*s = OrderStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Request body for paying for an existing order.
// Ref: #/components/schemas/pay_order_request
type PayOrderRequest struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// Response body after a successful payment of an order.
// Ref: #/components/schemas/pay_order_response
type PayOrderResponse struct {
	Order Order `json:"order"`
}

// GetOrder returns the value of Order.
func (s *PayOrderResponse) GetOrder() Order {
	return s.Order
}

// SetOrder sets the value of Order.
func (s *PayOrderResponse) SetOrder(val Order) {
	s.Order = val
}

func (*PayOrderResponse) payOrderRes() {}

// Payment method used to pay for the spacecraft build order.
// Ref: #/components/schemas/payment_method
type PaymentMethod string

const (
	PaymentMethodUNKNOWN       PaymentMethod = "UNKNOWN"
	PaymentMethodCARD          PaymentMethod = "CARD"
	PaymentMethodSBP           PaymentMethod = "SBP"
	PaymentMethodCREDITCARD    PaymentMethod = "CREDIT_CARD"
	PaymentMethodINVESTORMONEY PaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all PaymentMethod values.
func (PaymentMethod) AllValues() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodUNKNOWN,
		PaymentMethodCARD,
		PaymentMethodSBP,
		PaymentMethodCREDITCARD,
		PaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PaymentMethodUNKNOWN:
		return []byte(s), nil
	case PaymentMethodCARD:
		return []byte(s), nil
	case PaymentMethodSBP:
		return []byte(s), nil
	case PaymentMethodCREDITCARD:
		return []byte(s), nil
	case PaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentMethod) UnmarshalText(data []byte) error {
	switch PaymentMethod(data) {
	case PaymentMethodUNKNOWN:
		*s = PaymentMethodUNKNOWN
		return nil
	case PaymentMethodCARD:
		*s = PaymentMethodCARD
		return nil
	case PaymentMethodSBP:
		*s = PaymentMethodSBP
		return nil
	case PaymentMethodCREDITCARD:
		*s = PaymentMethodCREDITCARD
		return nil
	case PaymentMethodINVESTORMONEY:
		*s = PaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
// Ref: #/components/schemas/rate_limit_error
type RateLimitError struct {
	// Merged property.
	Code string `json:"code"`
	// Merged property.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *RateLimitError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *RateLimitError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *RateLimitError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *RateLimitError) SetMessage(val string) {
	s.Message = val
}

func (*RateLimitError) cancelOrderRes() {}
func (*RateLimitError) createOrderRes() {}
func (*RateLimitError) getOrderRes()    {}
func (*RateLimitError) payOrderRes()    {}

// Merged schema.
// Ref: #/components/schemas/service_unavailable_error
type ServiceUnavailableError struct {
	// Merged property.
	Code string `json:"code"`
	// Merged property.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ServiceUnavailableError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ServiceUnavailableError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ServiceUnavailableError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ServiceUnavailableError) SetMessage(val string) {
	s.Message = val
}

func (*ServiceUnavailableError) cancelOrderRes() {}
func (*ServiceUnavailableError) createOrderRes() {}
func (*ServiceUnavailableError) getOrderRes()    {}
func (*ServiceUnavailableError) payOrderRes()    {}

// Merged schema.
// Ref: #/components/schemas/unauthorized_error
type UnauthorizedError struct {
	// Merged property.
	Code string `json:"code"`
	// Merged property.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *UnauthorizedError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *UnauthorizedError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *UnauthorizedError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *UnauthorizedError) SetMessage(val string) {
	s.Message = val
}

func (*UnauthorizedError) cancelOrderRes() {}
func (*UnauthorizedError) createOrderRes() {}
func (*UnauthorizedError) getOrderRes()    {}
func (*UnauthorizedError) payOrderRes()    {}

// Merged schema.
// Ref: #/components/schemas/validation_error
type ValidationError struct {
	// Merged property.
	Code string `json:"code"`
	// Merged property.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ValidationError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ValidationError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ValidationError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ValidationError) SetMessage(val string) {
	s.Message = val
}

func (*ValidationError) createOrderRes() {}
func (*ValidationError) getOrderRes()    {}
