// Code generated by ogen, DO NOT EDIT.

package null

// setDefaults set default value of fields.
func (s *BadGatewayError) setDefaults() {
	{
		val := string("BAD_GATEWAY")
		s.Code = val
	}
	{
		val := string("Bad gateway.")
		s.Message = val
	}
}

// setDefaults set default value of fields.
func (s *BadRequestError) setDefaults() {
	{
		val := string("BAD_REQUEST")
		s.Code = val
	}
	{
		val := string("Request is invalid or malformed.")
		s.Message = val
	}
}

// setDefaults set default value of fields.
func (s *ConflictError) setDefaults() {
	{
		val := string("CONFLICT")
		s.Code = val
	}
	{
		val := string("Request conflicts with the current state of the resource.")
		s.Message = val
	}
}

// setDefaults set default value of fields.
func (s *ForbiddenError) setDefaults() {
	{
		val := string("FORBIDDEN")
		s.Code = val
	}
	{
		val := string("Access to this resource is forbidden.")
		s.Message = val
	}
}

// setDefaults set default value of fields.
func (s *InternalServerError) setDefaults() {
	{
		val := string("INTERNAL_SERVER_ERROR")
		s.Code = val
	}
	{
		val := string("An internal server error occurred.")
		s.Message = val
	}
}

// setDefaults set default value of fields.
func (s *NotFoundError) setDefaults() {
	{
		val := string("NOT_FOUND")
		s.Code = val
	}
	{
		val := string("Requested resource was not found.")
		s.Message = val
	}
}

// setDefaults set default value of fields.
func (s *RateLimitError) setDefaults() {
	{
		val := string("RATE_LIMIT_EXCEEDED")
		s.Code = val
	}
	{
		val := string("Too many requests, please try again later.")
		s.Message = val
	}
}

// setDefaults set default value of fields.
func (s *ServiceUnavailableError) setDefaults() {
	{
		val := string("SERVICE_UNAVAILABLE")
		s.Code = val
	}
	{
		val := string("Service is temporarily unavailable, please try again later.")
		s.Message = val
	}
}

// setDefaults set default value of fields.
func (s *UnauthorizedError) setDefaults() {
	{
		val := string("UNAUTHORIZED")
		s.Code = val
	}
	{
		val := string("Authentication is required or has failed.")
		s.Message = val
	}
}

// setDefaults set default value of fields.
func (s *ValidationError) setDefaults() {
	{
		val := string("VALIDATION_ERROR")
		s.Code = val
	}
	{
		val := string("Request validation failed.")
		s.Message = val
	}
}
